// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQa3R6ySGtHg3bsMHF6D-u-QChJtdOJUc',
    appId: '1:972835116380:web:74ac6f9cac8bd28027dd99',
    messagingSenderId: '972835116380',
    projectId: 'social-media-app-67842',
    authDomain: 'social-media-app-67842.firebaseapp.com',
    storageBucket: 'social-media-app-67842.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKqkDLn6L1Rm4nITXCvBmBDu0pRSD2YcM',
    appId: '1:972835116380:android:2801a784b53a62a027dd99',
    messagingSenderId: '972835116380',
    projectId: 'social-media-app-67842',
    storageBucket: 'social-media-app-67842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ_Gqc4uzGNnZrtQ5JEp1JXHza4M53g-0',
    appId: '1:972835116380:ios:35ce4d626f8a843827dd99',
    messagingSenderId: '972835116380',
    projectId: 'social-media-app-67842',
    storageBucket: 'social-media-app-67842.appspot.com',
    iosClientId: '972835116380-4i78m9fnl2ukp8moivitcrddjiqie26t.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ_Gqc4uzGNnZrtQ5JEp1JXHza4M53g-0',
    appId: '1:972835116380:ios:ed9aba162031f56e27dd99',
    messagingSenderId: '972835116380',
    projectId: 'social-media-app-67842',
    storageBucket: 'social-media-app-67842.appspot.com',
    iosClientId: '972835116380-fh91r34n29296n8vklrbrols4gv1f4g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
